#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Crypt-GeneratePassword
Version  : 0.05
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Crypt-GeneratePassword-0.05.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Crypt-GeneratePassword-0.05.tar.gz
Summary  : 'generate secure random pronounceable passwords'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Crypt-GeneratePassword-man

%description
This archive contains the distribution Crypt-GeneratePassword,
version 0.05:
generate secure random pronounceable passwords

%package man
Summary: man components for the perl-Crypt-GeneratePassword package.
Group: Default

%description man
man components for the perl-Crypt-GeneratePassword package.


%prep
%setup -q -n Crypt-GeneratePassword-0.05

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Crypt/GeneratePassword.pm
/usr/lib/perl5/site_perl/5.26.1/Crypt/GeneratePassword/de.pm
/usr/lib/perl5/site_perl/5.26.1/Crypt/GeneratePassword/en.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Crypt::GeneratePassword.3
